language: python
python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
        - "3.9"

# Install dependencies:
install:
        - pip install -r requirements.txt

# Run Tests
script:
        - pytest
